version: "3"
services:
  app:
    build: .
    ports:
      - "80:8443"
    env_file:
      - .env
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Seoul
